name: version-sync

on:
  pull_request:
  push:
    branches: [main]

jobs:
  mephisto-task-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Mephisto
        run: pip install -e .
      - name: Run version sync script
        run: python scripts/sync_mephisto_task.py check
